apply plugin: 'maven-publish'

def GROUP_ID = project.hasProperty('GROUP') ? GROUP : 'com.github.buhuiming'
def ARTIFACT_ID = project.hasProperty('POM_ARTIFACT_ID') ? POM_ARTIFACT_ID : project.name
def VERSION = project.hasProperty('VERSION_NAME') ? VERSION_NAME : '1.0.0'

afterEvaluate {
    publishing {
        publications {
            // 这个mavenJava可以随便填，只是一个任务名字而已
            // MavenPublication必须有，这个是调用的任务类
            mavenJava(MavenPublication) {
                // 这里头是artifacts的配置信息，不填会采用默认的
                groupId = GROUP_ID
                artifactId = ARTIFACT_ID
                version = VERSION

                from components.release
                if (!project.plugins.hasPlugin('kotlin-android')) {
                    artifact tasks.named("androidSourcesJar").get()
                }
            }
        }
    }
    // 显式声明任务依赖关系
    tasks.matching { it.name.startsWith("generateMetadataFileFor") }.configureEach {
        dependsOn tasks.named("androidSourcesJar")
    }
}
// 用于打包源代码的任务
tasks.register('androidSourcesJar', Jar) {
    archiveClassifier.set('sources')
    from android.sourceSets.main.java.srcDirs
}
