plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'maven-publish'
}

android {
    compileSdk 35

    defaultConfig {
        minSdk 26
        targetSdk 35

        vectorDrawables.useSupportLibrary = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        buildConfig true
    }
    lintOptions {
        abortOnError false
    }
    namespace "com.luck.picture.lib"
    kotlinOptions {
        jvmTarget = '17'
    }
}

ext {
    PUBLISH_ARTIFACT_ID = "PictureSelector"
}

ext.GROUP = "com.github.buhuiming"
ext.POM_ARTIFACT_ID = "PictureSelector"
ext.VERSION_NAME = "3.12.0"
//引用gradle_upload.gradle
apply from: "${project.rootDir}/publish.gradle"

afterEvaluate {
    publishing {
        publications {
            // 这个mavenJava可以随便填，只是一个任务名字而已
            // MavenPublication必须有，这个是调用的任务类
            mavenJava(MavenPublication) {
                // 这里头是artifacts的配置信息，不填会采用默认的
                groupId = 'com.github.buhuiming'
                artifactId = 'PictureSelector'
                version = '3.12.0'

                from components.release
                artifact tasks.named('PictureSelector').get() //打包源码，去除这行打的包将看不到源码
            }
        }
    }
}
// 用于打包源代码的任务
tasks.register('PictureSelector', Jar) {
    archiveClassifier.set('sources')
    from android.sourceSets.main.java.srcDirs
}

dependencies {
    implementation "androidx.appcompat:appcompat:${cfgs.version_appcompat}"
    implementation "androidx.recyclerview:recyclerview:${cfgs.version_recyclerview}"
    implementation "androidx.activity:activity:${cfgs.activity_version}"
    implementation "androidx.fragment:fragment:${cfgs.fragment_version}"
    implementation "androidx.exifinterface:exifinterface:${cfgs.exifinterface_version}"
    implementation "androidx.viewpager2:viewpager2:${cfgs.viewpage2}"
    implementation "androidx.constraintlayout:constraintlayout:${cfgs.constraintlayout}"
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.activity:activity-ktx:1.10.1'
}
